//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Film_Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Film_Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @import url(http://fonts.googleapis.com/css?family=Crimson+Text);
        ///@import url(http://fonts.googleapis.com/css?family=Droid+Sans);
        ///@import url(http://fonts.googleapis.com/css?family=Droid+Serif);
        ///@import url(http://fonts.googleapis.com/css?family=Cardo);
        ///
        ///#SORT_TITLE, #SORT_RATING, #SORT_RUNTIME, #SORT_YEAR, #SORT_DIRTIME {
        ///font-weight:normal !important;
        ///border:0 !important;
        ///background:none !important;
        ///text-decoration:none !important;
        ///margin:0 10px 0 0 !important;
        ///}
        ///body {
        ///background:#111111 !important;
        ///colo [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /*
        ///    Simple Movie Catalog (javascript)
        ///    Copyright (C) 2008-2010 damien.langg@gmail.com
        ///    License: GPL &lt;http://www.gnu.org/licenses/&gt;
        ///*/
        ///
        ///var initialized = false;
        ///var debug_enabled = false;
        ///var debug_obj = new Object();
        ///var current_sort;
        ///var current_dir = 1;
        ///var sort_steps = 0;
        ///
        ///window.onload = moviecat_init;
        ///
        ///function moviecat_init()
        ///{
        ///    if (get_url_param(&quot;debug&quot;)) debug_enabled = true;
        ///    if (debug_enabled) enable_debug();
        ///    initialized = true;
        ///    active_sort(&quot;SORT_TITLE&quot;, 1);
        ///    init_filter( [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string MovieCat {
            get {
                return ResourceManager.GetString("MovieCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nocover {
            get {
                object obj = ResourceManager.GetObject("nocover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .movietable {
        ///background: whitesmoke;
        ///}
        ///
        ///.noposter {
        ///background: gray;
        ///}
        ///
        ///.title {
        ///background: lightblue;
        ///} ähnelt.
        /// </summary>
        internal static string Old {
            get {
                return ResourceManager.GetString("Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;table width=&quot;100%&quot; cellspacing=&quot;0&quot; class=&quot;movietable&quot;&gt;
        ///&lt;tbody&gt;&lt;tr&gt;
        ///&lt;td class=&quot;poster&quot; rowspan=&quot;4&quot; width=&quot;95&quot;&gt;&lt;img src=&quot;{0}&quot;&gt;&lt;/td&gt;
        ///&lt;td class=&quot;title&quot; height=&quot;1*&quot;&gt;&lt;b&gt;&amp;nbsp;
        ///&lt;a class=&quot;MTITLE&quot; href=&quot;{1}&quot;&gt;{2}&lt;/a&gt;&lt;/b&gt;
        /// (&lt;span class=&quot;MYEAR&quot;&gt;{3}&lt;/span&gt;) &amp;nbsp; &lt;small&gt;&lt;i&gt;&lt;/i&gt;&lt;/small&gt;
        ///&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr class=&quot;moviedesc&quot;&gt;&lt;td height=&quot;1*&quot;&gt;
        ///FSK: {4} &amp;nbsp;&amp;nbsp; Runtime: &lt;b class=&quot;MRUNTIME&quot;&gt;{5}&lt;/b&gt; min &amp;nbsp;&amp;nbsp; &lt;i class=&quot;MGENRE&quot;&gt;({6})&lt;/i&gt;
        ///&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr class=&quot;moviedesc&quot;&gt;&lt;td class=&quot;plot&quot;&gt;&lt;font size=&quot;-1&quot;&gt;
        /// {7} [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;/tbody&gt;&lt;/table&gt;
        ///&lt;br&gt;&lt;div align=&quot;right&quot;&gt;&lt;font size=&quot;-2&quot;&gt;&lt;i&gt;Generiert vom Filmmanager von Vincent&lt;/i&gt;&lt;/font&gt;&lt;/div&gt;
        ///
        ///&lt;/body&gt;&lt;/html&gt; ähnelt.
        /// </summary>
        internal static string WebsiteBottom {
            get {
                return ResourceManager.GetString("WebsiteBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;!-- saved from url=(0050)http://smoviecat.sourceforge.net/demo/catalog.html --&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; lang=&quot;en-US&quot; xml:lang=&quot;en-US&quot;&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=ISO-8859-1&quot;&gt;
        ///&lt;title&gt;Vincents Filme&lt;/title&gt;
        ///
        ///&lt;script src=&quot;./files/moviecat.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///&lt;link type=&quot;text/css&quot; rel=&quot;alternate stylesheet&quot; href [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string WebsiteHeader {
            get {
                return ResourceManager.GetString("WebsiteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @import url(http://fonts.googleapis.com/css?family=Crimson+Text);
        ///@import url(http://fonts.googleapis.com/css?family=Droid+Sans);
        ///@import url(http://fonts.googleapis.com/css?family=Droid+Serif);
        ///@import url(http://fonts.googleapis.com/css?family=Cardo);
        ///
        ///#SORT_TITLE, #SORT_RATING, #SORT_RUNTIME, #SORT_YEAR, #SORT_DIRTIME {
        ///font-weight:normal !important;
        ///border:0 !important;
        ///background:none !important;
        ///text-decoration:none !important;
        ///margin:0 10px 0 0 !important;
        ///}
        ///body {
        ///background:#ffffff !important;
        ///colo [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
    }
}
